set -u
V=.review/venv/bin/python
run() { name="$1"; img="$2"; q="$3"; echo "=== $name"; $V .review/vlm.py "$img" "$q" > ".review/vlm-out/$name.txt" 2>&1; echo "done $name"; }
run T_tasksL .review/crops/z_tasks_L.png "This is a crop of a Markdown reader's task list (light theme, 2x scale). There are three task items. Answer these questions LITERALLY and carefully, one by one: (1) For EACH item, is the checkbox on the SAME horizontal line as its text, or is the checkbox on a line ABOVE the text? (2) Is the task text indented to the right of the checkbox, or does it start at the same left x position as the checkbox? (3) Which items have a strikethrough line through the text? (4) Does the strikethrough line also pass through any checkbox? (5) Estimate the vertical gap between one item's checkbox and the same item's text, compared to the text line height. Do not guess; describe only what the pixels show."
run T_task1 .review/crops/z_task1_L.png "This is a 2x zoomed crop of ONE task list item in a Markdown reader (light theme). Describe the exact vertical arrangement: is the checkbox square immediately to the left of the text on the same baseline, or is it above the text? Where exactly is the text relative to the checkbox? Give coordinates in the image if you can."
run T_task2 .review/crops/z_task2_L.png "This is a 2x zoomed crop of ONE COMPLETED task list item in a Markdown reader (light theme). Describe the exact vertical arrangement of the filled checkbox and the text. Is the checkbox to the left of the text on the same line? Does the strikethrough line pass through the checkbox, or only through the text? How does this look quality-wise?"
run T_tableL .review/crops/z_table_L.png "This is a crop of a Markdown reader's table (light theme, 2x). Answer literally: (1) How many columns and how many body rows? (2) Do the header cells look vertically centred or floating oddly in their row? (3) Are there visible horizontal lines between the BODY rows and around the outside of the table? Describe how visible each line is. (4) Is the last column much wider than the others? (5) Is the cell text too close to the left edge of the cell? (6) Anything that looks like a rendering bug?"
run T_codeL .review/crops/z_code_L.png "This is a crop of a fenced TypeScript code block in a Markdown reader (light theme, 2x). Answer literally: (1) List every distinct text colour you can see and say which words have it. (2) Is the highlighting sparse (only a few words coloured) or rich? (3) Does the box look like it ends well before the right edge of the surrounding text column? (4) Any clipping, cut-off characters, or misalignment?"
run T_tbLeft .review/crops/z_tbL_left.png "This is the LEFT half of the title bar of a desktop Markdown reader (light theme, 2x). The app is on macOS. Describe every icon you see and its position. Is there a large empty area at the far left? Does the empty area look like space reserved for something, or does it look accidentally empty? Is anything misaligned or odd?"
run T_tbRight .review/crops/z_tbL_right.png "This is the RIGHT portion of the title bar of a desktop Markdown reader (light theme, 2x, macOS). Describe every icon and its spacing. Do the icons look evenly spaced and visually consistent? Does anything look missing or cramped?"
run T_tbWin .review/crops/z_tbW_right.png "This is the RIGHT portion of the title bar of the same Markdown reader but rendered in a Windows variant (light theme, 2x). There should be window caption buttons (minimise, maximise, close). Answer: (1) Are the window caption buttons visible? Describe them, their size and exact position relative to the window's top-right corner. (2) Do they look like native Windows 11 caption buttons, or like something drawn by the app? (3) Is the bar height and button placement consistent with a real Windows app? Be blunt."
run T_tbWinFull .review/crops/z_tbW_left.png "This is the LEFT+MIDDLE portion of the title bar of a Markdown reader rendered in its Windows variant (light theme, 2x). Answer: is the window title text centred in the middle of the bar, or left-aligned near the left edge? On a real Windows app, where would the title be? Also describe every icon you see and any empty space."
run T_h1quoteL .review/crops/z_h1_quote_L.png "This is a crop of a Markdown reader (light theme, 2x) showing the document H1 title and a blockquote underneath. Answer literally: (1) How big does the H1 look relative to the quote text - too big, right, too small? (2) Describe the blockquote's left bar: colour, thickness, is it clearly visible? (3) Does the blockquote have any background fill that differs from the page? (4) Is the gap between the H1 and the blockquote too big, too small, or right? (5) Anything that looks like a mistake?"
run T_quoteZoom .review/crops/z_quote_L.png "This is a 2x zoomed crop of a blockquote in a Markdown reader (light theme). The left vertical bar is visible. Answer: is the quote text indented enough from the bar? Is the bar thick enough to read as a deliberate design element? Does the quote look like a deliberate quote or like an accident? Is the quote text darker or lighter than normal body text?"
run T_tasksD .review/crops/z_tasks_D.png "This is a crop of a Markdown reader's task list (DARK theme, 2x). Answer literally: (1) For each of the three items, is the checkbox on the same line as the text or on the line ABOVE it? (2) Do the filled checkboxes show a visible check mark glyph, or are they just solid filled squares with no tick? (3) Do the strikethroughs read well? (4) Any contrast or legibility problem?"
run T_tableD .review/crops/z_table_D.png "This is a crop of a Markdown reader's table (DARK theme, 2x). Answer literally: (1) Are the horizontal row separator lines and the table's outer border visible, or almost invisible? (2) Is the header row visually distinguished from body rows, and how? (3) Is the last column much wider than the others? (4) Anything that looks like a bug?"
run T_codeD .review/crops/z_code_D.png "This is a crop of a fenced TypeScript code block in a Markdown reader (DARK theme, 2x). Answer literally: (1) List every distinct text colour you see and which words have it. (2) Is the highlighting sparse or rich? (3) Does the code block background differ clearly from the page background? (4) Any clipping or alignment problem?"
run T_h1quoteD .review/crops/z_h1_quote_D.png "This is a crop of a Markdown reader (DARK theme, 2x) showing the H1 title and a blockquote. Answer literally: (1) Is the blockquote's left bar clearly visible against the dark page, or nearly invisible? (2) Does the blockquote text look dimmer or the same as normal body text? (3) Is the gap between H1 and the quote right? (4) Anything that looks like a mistake in dark mode specifically?"
