set -u
V=.review/venv/bin/python
run() { name="$1"; img="$2"; q="$3"; echo "=== $name"; $V .review/vlm.py "$img" "$q" > ".review/vlm-out/$name.txt" 2>&1; echo "done $name"; }
run titlebar_light .review/crops/light_titlebar_full.png "This is the top titlebar strip of a small desktop Markdown reader app (light theme, 2x scale). Describe everything you see left to right: buttons, icons, the centered title text. Are the icons evenly spaced and balanced with the title? Does the titlebar look crowded, empty, or well proportioned? Is anything overlapping, misaligned, too small, or blurry? Is the whole strip a natural height for a modern app? Be as literal as possible; do not invent elements."
run h1_quote .review/crops/light_h1_quote.png "This is a crop of a Markdown reader (light theme) showing an H1 heading and a blockquote below it. Judge the typography and the vertical spacing between the heading and the quote. Is there too much or too little space? Does the blockquote look like a proper quote (left bar, indent, background)? Is anything visually off, clipped, or missing? Be literal and concise."
run h2_para .review/crops/light_h2_para.png "This is a crop of a Markdown reader (light theme) with an H2 heading above a paragraph containing bold text, inline code chips, and a link. Judge: (1) heading to paragraph spacing, (2) do the inline code chips look good or cheap, (3) does the link colour look right, (4) is the CJK+Latin mixed line spacing smooth. Point out anything that looks like a mistake."
run tasks .review/crops/light_tasks.png "This is a crop of a Markdown reader (light theme) showing a task list with checkboxes, some checked. Describe each item. For the checked items: is there a line-through (strikethrough) through the text, and does it read well or does it look ugly/misplaced/offset? Are the checkboxes aligned with the first line of text? Is the wrapped continuation line aligned correctly? Anything clipped or overlapping?"
run code .review/crops/light_code.png "This is a crop of a Markdown reader (light theme) showing a fenced TypeScript code block with syntax highlighting. Judge the syntax highlighting honestly: do the token colours look correct and harmonious, or noisy/random/wrong (for example keywords, identifiers, strings, and comments coloured in a way that looks arbitrary)? Is the code block box sized well? Is the monospace text evenly spaced and fully visible, nothing clipped? Is the line spacing right? Does it look like a professional code block?"
run hr_tail .review/crops/light_hr_tail.png "This is a crop of a Markdown reader (light theme) showing a horizontal rule and a paragraph after it. Describe what you see. Does the horizontal rule look like a deliberate divider, is it the right length and position, does it read as a divider or as a mistake? Is the spacing above and below it sensible?"
run bottom_empty .review/crops/light_bottom_empty.png "This is the bottom portion of a full-page screenshot of a Markdown reader app. Describe what you see, including whether a scrollbar or any element is visible. Is this mostly empty space?"
run full_light .shots/verify-light.png "This is a screenshot of a small desktop Markdown reading app (light theme, 1200x820 CSS). Give an honest overall design critique. What looks polished, and what looks wrong, cheap, unbalanced, or like a mistake? Be specific about location (e.g. the toolbar row, the heading spacing, the table). Do not invent elements you cannot see."
run full_dark .shots/verify-dark.png "This is a screenshot of a small desktop Markdown reading app (dark theme, 1200x820 CSS). Give an honest overall design critique. What looks polished, and what looks wrong, cheap, unbalanced, or like a mistake? Be specific about location. Then compare: does this dark theme look as good as a light theme would, and what feels weaker?"
